# Generated by Django 5.1.6 on 2025-02-24 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(default='', max_length=5)),
                ('name', models.CharField(default='', max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('images', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(default='', max_length=5)),
                ('name', models.CharField(default='', max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('images', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(default='', max_length=5)),
                ('name', models.CharField(default='', max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('images', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='', max_length=5)),
                ('name', models.CharField(default='', max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('images', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.category')),
            ],
        ),
    ]
