# Generated by Django 5.1.6 on 2025-02-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='category',
            field=models.CharField(default='คอมพิวเตอร์', max_length=50),
        ),
    ]
