# Generated by Django 5.1.6 on 2025-02-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0002_alter_computer_category'),
    ]

    operations = [
    ]
