# Generated by Django 5.1.6 on 2025-02-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0003_auto_20250226_1723'),
    ]

    operations = [
    ]
