# Generated by Django 5.1.6 on 2025-02-26 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0004_auto_20250226_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='id',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='id',
        ),
        migrations.AddField(
            model_name='computer',
            name='case',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='computer',
            name='cpu',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='computer',
            name='cpuCooler',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='computer',
            name='mainboard',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='computer',
            name='ram',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='computer',
            name='storage',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='aid',
            field=models.CharField(default='', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='images',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='brand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='computer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.category'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='id',
            field=models.CharField(default='', max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='computer',
            name='images',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='images',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='mid',
            field=models.CharField(default='', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='printer',
            name='images',
            field=models.ImageField(default='', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='pid',
            field=models.CharField(default='', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='printer',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
