# Generated by Django 5.1.6 on 2025-02-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0005_remove_accessories_id_remove_monitor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
