# Generated by Django 5.1.6 on 2025-02-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0008_alter_computer_cid_alter_computer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='id',
        ),
    ]
